### ISSUE TITLE
Keybindings not set up

### ISSUE THREAD

**Issue by pavelkogan** [cydparser/spacemacs-intero#1]
When loading `intero-mode`, I get the following error:
```
Error (use-package): intero :config: Symbol's value as variable is void: haskell-modes
```
`intero-mode` still works, but spacemacs keybindings aren't set up.

Adding the following line before `haskell-modes` is first used in `packages.el` seems to fix it:
```
(defvar haskell-modes '(haskell-mode))
```

**Comment by cydparser** [comment]
Thanks for reporting. `haskell-modes` is defined in the develop branch of spacemacs (which I use). I've added it to `config.el`.
