### ISSUE TITLE
Fails to load initially

### ISSUE THREAD

**Issue by pavelkogan** [cydparser/spacemacs-intero#2]
When loading a Haskell source file after starting spacemacs before loading anything else that requires flycheck, `intero-mode` fails to load with the following error:
```
File mode specification error: (void-variable flycheck-disabled-checkers)
```
Running `intero-mode` manually works and it loads automatically for files opened later.

**Comment by fatlazycat** [comment]
+1

**Comment by cydparser** [comment]
Thanks for reporting. The issue should now be fixed.
