### ISSUE TITLE
option not to display the type on cursor movement?

### ISSUE THREAD

**Issue by emmanueltouzery** [cydparser/spacemacs-intero#3]
currently spacemacs+this layer on my machine is displaying the type of the variable under the cursor in the status bar. And updating it on cursor move. My home computer is quite old nowadays and that's really making it unusably slow, plus I find that distracting. I looked at the source of this layer and the emacs intero integration itself and I have no idea where is the code doing that :(
Is that code in this layer, and if yes, could there be an option to disable it? If not I'd love a hint as to where it is :(

Thanks for the very useful layer!

**Comment by cydparser** [comment]
Intero does not automatically display types for me. Do you have `haskell-doc-mode` enabled in your config?

**Comment by emmanueltouzery** [comment]
no i don't. I tried `M-x haskell-doc-mode` and it enables it, run it again, it disables it, and the apidocs are still displayed. Ok so it must be something with my config... I guess I'll try to comment out stuff and try to track it down...
