### ISSUE TITLE
 Error on load: symbols value is void

### ISSUE THREAD

**Issue by mckeankylej** [cydparser/spacemacs-intero#5]
When installing this layer and restarting I get the following error: 
```sh
Error (use-package): intero :init: Symbol's value as variable is void: company-backends-haskell-mode
```
What am I doing wrong?

**Comment by cydparser** [comment]
That variable is defined by the Haskell layer. Are you using the latest, stable Spacemacs (0.105.21)?

**Comment by cydparser** [comment]
Auto completion is not working correctly for me even without that error: I'll investigate later.

**Comment by mckeankylej** [comment]
I am using latest spacemacs. Should I open a issue upstream if the issue is with intero?

**Comment by cydparser** [comment]
Nah, Intero doesn't define or use `company-backends-haskell-mode`. It is defined here https://github.com/syl20bnr/spacemacs/blob/master/layers/%2Blang/haskell/config.el#L14. Can you verify that `~/.emacs.d/layers/+lang/haskell/config.el` contains `(spacemacs|defvar-company-backends haskell-mode)`? If it does, try restarting Emacs.

**Comment by mckeankylej** [comment]
Not really sure what I did but nuking .emacs.d and reinstalling everything made it work. Very odd.

**Comment by sid-kap** [comment]
I'm having the same issue. My `~/.emacs.d/layers/+lang/haskell/config.el` does contain `(spacemacs|defvar-company-backends haskell-mode)`. Is there something else I can try to find the source of the problem?

**Comment by sid-kap** [comment]
I managed to work around this by just using the haskell layer instead, and not installing this layer. (Intero is now part of haskell layer, it seems.) Is that the new recommended way of using intero with spacemacs now?

**Comment by cydparser** [comment]
Yes, it is recommended to try Spacemacs' Haskell layer for Intero integration.

**Comment by sid-kap** [comment]
I see. Thanks for your reply!
